name: Collect lamppost weather (every 10 minutes)

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install conda and create env
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11
          channels: conda-forge
          # create env using mamba for speed
          run-conda: |
            mamba create -y -n lamppost-env python=3.11 geopandas pandas requests -c conda-forge

      - name: Run scraper inside conda env (no shell activation)
        run: |
          # Use `conda run` so we don't need to source conda.sh or rely on CONDA_PREFIX
          conda run -n lamppost-env python scrape.py --gdb smart_lamppost_fgdb.gdb --out out.csv
